# torch 数据类型

## 1.导入torch库并检验安装情况

In [2]:
import torch 
import torch.nn as nn #神经网络器模块
import torch.optim as optim #优化器模块
import numpy as np
import matplotlib
print(torch.__version__) #查看torch版本
print(torch.cuda.is_available()) #查看torch是否可以用gpu

2.4.1+cu124
True


In [3]:
a=torch.randn(2,3)
a.type()
type(a)
print(a.type())
print(type(a))

torch.FloatTensor
<class 'torch.Tensor'>


In [4]:
data=torch.randn(1,2)
data=data.cuda()
isinstance(data,torch.cuda.DoubleTensor)


False

In [5]:
isinstance(data,torch.cuda.FloatTensor)

True

In [17]:
data=torch.randn(1,2,dtype=torch.float64)
data=data.cuda()
isinstance(data,torch.cuda.DoubleTensor)

True

In [6]:
print(data.dtype)

torch.float32


## 2.数据类型

### 2.1 dim=0 
（用作标量）

In [40]:
a=torch.tensor(2.2)
a.shape

torch.Size([])

In [41]:
a.size

<function Tensor.size>

In [42]:
a.size()

torch.Size([])

In [43]:
len(a.shape)

0

### 2.2 dim=1
（bias,linear input)

In [33]:
b=torch.tensor([1.2])
b.shape

torch.Size([1])

In [34]:
b.size

<function Tensor.size>

In [35]:
b.size()

torch.Size([1])

In [37]:
len(b.shape)

1

In [58]:
data=np.ones(4)
data

array([1., 1., 1., 1.])

In [57]:
data=torch.from_numpy(data)
print(data)

tensor([1., 1., 1., 1.], dtype=torch.float64)


### 2.3 dim=2

In [62]:
a=torch.randn(2,3)
a

tensor([[ 0.3091, -0.0754,  0.5061],
        [ 0.3758, -0.8391,  0.5472]])

In [63]:
a.shape

torch.Size([2, 3])

In [64]:
a.size()

torch.Size([2, 3])

In [68]:
a.size(0)

2

In [69]:
a.size(1)

3

In [71]:
a.shape[1]

3

In [75]:
b=torch.zeros(3,dtype=a.dtype)
b

tensor([0., 0., 0.])

In [77]:
a.dtype

torch.float32

### 2.4 dim=3 

In [86]:
a=torch.rand(2,4,5)
a

tensor([[[0.9935, 0.4246, 0.5168, 0.5055, 0.9275],
         [0.5834, 0.6589, 0.3727, 0.6544, 0.8033],
         [0.2057, 0.0509, 0.5329, 0.5934, 0.5565],
         [0.9566, 0.6225, 0.9856, 0.8420, 0.3354]],

        [[0.8371, 0.2064, 0.3176, 0.0757, 0.4433],
         [0.4124, 0.2249, 0.0285, 0.2768, 0.2345],
         [0.2725, 0.4880, 0.8525, 0.6961, 0.5870],
         [0.0230, 0.9659, 0.0741, 0.0552, 0.9491]]])

In [87]:
a.shape

torch.Size([2, 4, 5])

In [88]:
a[0]

tensor([[0.9935, 0.4246, 0.5168, 0.5055, 0.9275],
        [0.5834, 0.6589, 0.3727, 0.6544, 0.8033],
        [0.2057, 0.0509, 0.5329, 0.5934, 0.5565],
        [0.9566, 0.6225, 0.9856, 0.8420, 0.3354]])

In [89]:
a[0].shape

torch.Size([4, 5])

### 2.5 dim=4

In [146]:
a=torch.rand(2,3,28,28)


In [92]:
a.numel() # numbel elements

4704

In [93]:
a.dim()

4

In [96]:
a[1].shape

torch.Size([3, 28, 28])

In [97]:
a.size(1)

3

## 3 创建torch数据

### 3.1  import from numpy

In [108]:
a=np.array([[2,3.3],[2,4]])
a

array([[2. , 3.3],
       [2. , 4. ]])

In [111]:
a.shape

(2, 2)

In [112]:
a.dtype

dtype('float64')

In [113]:
torch.from_numpy(a)

tensor([[2.0000, 3.3000],
        [2.0000, 4.0000]], dtype=torch.float64)

In [120]:
b=torch.tensor(a,dtype=torch.float16)
b

tensor([[2.0000, 3.3008],
        [2.0000, 4.0000]], dtype=torch.float16)

### 3.2 import from list 

In [121]:
torch.tensor([2,3])

tensor([2, 3])

In [122]:
torch.tensor([[2,3],[4,5]])

tensor([[2, 3],
        [4, 5]])

In [123]:
torch.ones(3)

tensor([1., 1., 1.])

In [124]:
torch.zeros(8)

tensor([0., 0., 0., 0., 0., 0., 0., 0.])

In [128]:
torch.ones(2,5,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [136]:
a=torch.Size([2,5,4])
b=torch.randn(a)
c=torch.zeros(a)
print(b)
print(c)

tensor([[[-0.5278,  1.2054,  1.5073,  0.9739],
         [ 0.8661,  0.7168,  0.1116, -2.1202],
         [ 0.5696, -0.4113,  0.2497,  0.8150],
         [-1.5565,  1.2621,  1.2977, -1.2128],
         [ 0.1018,  0.7821,  0.9251,  0.9403]],

        [[ 0.7573, -0.3246,  0.3033, -0.3044],
         [-2.4289, -1.1770, -0.2752, -0.5788],
         [-1.3912,  0.9544, -2.1216, -0.1773],
         [-0.7299,  1.8687,  0.6452,  0.0547],
         [ 1.5546,  0.6870,  0.2700,  0.2413]]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [144]:
d=torch.ones(16).reshape(4,2,-1)
d

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [145]:
e=torch.rand_like(d)
e

tensor([[[0.9461, 0.0460],
         [0.3758, 0.2398]],

        [[0.4041, 0.0754],
         [0.4190, 0.7825]],

        [[0.9752, 0.4452],
         [0.5416, 0.2265]],

        [[0.9034, 0.7251],
         [0.2865, 0.9684]]])

###  3.3 randn and normal
$randn：标准正态分布 N(0,1)$

$normal:均值为mean，方差为std的正态分布：N(u,std)$

In [147]:
a=torch.randn(3,3)
a

tensor([[-1.6935, -0.4004, -2.9485],
        [ 0.4336, -0.0613, -0.0951],
        [-0.5132,  0.6032,  0.2894]])

In [154]:
a_sum=a.reshape(9)
a_sum

tensor([-1.6935, -0.4004, -2.9485,  0.4336, -0.0613, -0.0951, -0.5132,  0.6032,
         0.2894])

In [156]:
a_sum=a_sum.sum()#数据量大时sum接近0
a_sum

tensor(-4.3859)

In [162]:
torch.normal(mean=torch.full([10],0).float(),std=torch.arange(1,0,-0.1).float())#normal中mean和std必须为浮点类型

tensor([-2.4830,  0.6692,  0.1537, -0.6566,  0.3903,  0.8072, -0.1299, -0.0375,
        -0.1777,  0.0933])

### 3.4 full,arange,range,linspace,logspace,ones,zeros,eye 

In [163]:
torch.full([2,3],8)

tensor([[8, 8, 8],
        [8, 8, 8]])

In [164]:
torch.full([2,3,5],7)

tensor([[[7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7]],

        [[7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7]]])

In [165]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [166]:
torch.range(1,10)#torch中被弃用

<ipython-input-166-a2647884754e>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [167]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [169]:
torch.arange(1,10,2).float().size()

torch.Size([5])

In [172]:
torch.linspace(0,10,2)

tensor([ 0., 10.])

In [173]:
torch.linspace(0,10,steps=2)

tensor([ 0., 10.])

In [174]:
torch.linspace(0,10,11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

torch.logspace(0,-1,11)  means $10^0,10^{-0.1},...,10^{-1}$

In [176]:
torch.logspace(0,-1,10)

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [177]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## 4 torch的索引与切片

### 4.1  ,  :  ::  ...

In [181]:
a=torch.rand(4,3,28,28)
a.shape

torch.Size([4, 3, 28, 28])

In [182]:
a[0].shape

torch.Size([3, 28, 28])

In [183]:
a[0,0].shape

torch.Size([28, 28])

In [184]:
a[0,0,0,0].shape

torch.Size([])

In [186]:
a[1,1,1,1].dim()

0

In [188]:
a[:2].shape # 不包含2

torch.Size([2, 3, 28, 28])

In [189]:
a[:2,:2].shape

torch.Size([2, 2, 28, 28])

In [191]:
a[:2,:1,:,:].shape

torch.Size([2, 1, 28, 28])

In [193]:
a[:-1].shape

torch.Size([3, 3, 28, 28])

In [194]:
a[:-3].shape

torch.Size([1, 3, 28, 28])

In [195]:
a[:,:,0:28:2,0:4:2].shape

torch.Size([4, 3, 14, 2])

In [196]:
a[::2,:,:,::2].shape

torch.Size([2, 3, 28, 14])

In [206]:
torch.arange(14)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [207]:
a[...].shape

torch.Size([4, 3, 28, 28])

In [208]:
a[1,...].shape

torch.Size([3, 28, 28])

### 4.2 index_select,mask,take

In [204]:
a.index_select(3,torch.arange(14)).shape #某指定维度索引

torch.Size([4, 3, 28, 14])

In [203]:
a.index_select(1,torch.arange(2)).shape

torch.Size([4, 2, 28, 28])

In [211]:
x=torch.randn(3,4)
x

tensor([[-0.5267,  1.0655, -0.0044, -0.9527],
        [-0.2434,  0.9681,  0.9670, -0.0776],
        [-0.0058,  0.1203,  0.1239, -0.3819]])

In [213]:
mask=x.ge(0.5)
mask

tensor([[False,  True, False, False],
        [False,  True,  True, False],
        [False, False, False, False]])

In [220]:
torch.masked_select(x,mask)   #索引mask=true的值

tensor([1.0655, 0.9681, 0.9670])

In [218]:
a=torch.tensor([[4,5,6],[7,8,9],[10,11,12]])
a

tensor([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [219]:
torch.take(a,torch.tensor([1,4,7]))  #维度展开后索引

tensor([ 5,  8, 11])

## 5.维度变换

### 5.1 view reshape

In [221]:
a=torch.rand(4,1,28,28)
a.shape

torch.Size([4, 1, 28, 28])

In [223]:
a.reshape(4,1,-1).shape

torch.Size([4, 1, 784])

In [225]:
a.view(4,-1).shape

torch.Size([4, 784])

In [226]:
a.reshape(-1,28).shape

torch.Size([112, 28])

In [228]:
a.view(-1,28).shape

torch.Size([112, 28])

### 5.2 squeeze unsqueeze

In [229]:
a.shape

torch.Size([4, 1, 28, 28])

In [232]:
print(a.unsqueeze(0).shape)
print(a.unsqueeze(1).shape)
print(a.unsqueeze(4).shape)

torch.Size([1, 4, 1, 28, 28])
torch.Size([4, 1, 1, 28, 28])
torch.Size([4, 1, 28, 28, 1])


In [233]:
print(a.unsqueeze(-1).shape)
print(a.unsqueeze(-2).shape)
print(a.unsqueeze(-4).shape)

torch.Size([4, 1, 28, 28, 1])
torch.Size([4, 1, 28, 1, 28])
torch.Size([4, 1, 1, 28, 28])


In [238]:
b=torch.tensor([1,2,3,4,5,6,7,8])
print(b.shape)
b

torch.Size([8])


tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [239]:
print(b.unsqueeze(1))
print(b.unsqueeze(0))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])
tensor([[1, 2, 3, 4, 5, 6, 7, 8]])


In [251]:
print(b.unsqueeze(1).unsqueeze(2).shape)
#print(b.unsqueeze(1).unsqueeze(2))
print(b.unsqueeze(0).unsqueeze(1).shape)
#print(b.unsqueeze(0).unsqueeze(2))

torch.Size([1, 1, 1, 1, 28, 1])
torch.Size([1, 1, 1, 1, 28, 1])


In [246]:
print(a.shape)
print(a.squeeze().shape)
print(a.squeeze().squeeze().shape)
print(a.squeeze(1).shape)

torch.Size([4, 1, 28, 28])
torch.Size([4, 28, 28])
torch.Size([4, 28, 28])
torch.Size([4, 28, 28])


In [250]:
b=torch.randn(1,1,28,1)
print(b.shape)
print(b.squeeze().shape)
print(b.squeeze(1).shape)

torch.Size([1, 1, 28, 1])
torch.Size([28])
torch.Size([1, 28, 1])


### 5.3 expand,repeat

In [253]:
print(b.shape)
print(b.expand(4,2,28,2).shape) # only 1 can expand

torch.Size([1, 1, 28, 1])
torch.Size([4, 2, 28, 2])


In [261]:
a=torch.tensor([[[1,2,3],[4,5,6]]])
print(a.shape)
print(a)
print(a.expand(2,2,3).shape)
print(a.expand(2,2,3))
print(a.expand(4,2,3).shape)
print(a.expand(4,2,3))

torch.Size([1, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]]])
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])
torch.Size([4, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])


In [272]:
a=torch.randn(1,2,3)
print(a.shape)
print(a)
print(a.repeat(1,2,1).shape)
print(a.repeat)
print(a.repeat(9,9,9).shape)

torch.Size([1, 2, 3])
tensor([[[-0.8392, -0.7886, -1.1528],
         [ 0.1487,  0.5555, -0.0434]]])
torch.Size([1, 4, 3])
<built-in method repeat of Tensor object at 0x000001F6D755B900>
torch.Size([9, 18, 27])


In [271]:
a.repeat(1,2,2)

tensor([[[-1.7835,  0.5557,  0.1043, -1.7835,  0.5557,  0.1043],
         [ 0.4131, -0.0029, -0.3700,  0.4131, -0.0029, -0.3700],
         [-1.7835,  0.5557,  0.1043, -1.7835,  0.5557,  0.1043],
         [ 0.4131, -0.0029, -0.3700,  0.4131, -0.0029, -0.3700]]])

### 5.4 .t() ,transpose,permute

In [273]:
a=torch.rand(2,3)
print(a.shape)
print(a)
b=a.t()  # only dim=2 
print(b.shape)
print(b)

torch.Size([2, 3])
tensor([[0.5800, 0.4139, 0.1943],
        [0.0064, 0.9427, 0.5836]])
torch.Size([3, 2])
tensor([[0.5800, 0.0064],
        [0.4139, 0.9427],
        [0.1943, 0.5836]])


In [276]:
a=torch.rand(2,3,4)
print(a.shape)
print(a)
print(a.transpose(0,1).shape)
print(a.transpose(0,1))
print(a.transpose(1,2))
print(a.transpose(0,2))

torch.Size([2, 3, 4])
tensor([[[0.0052, 0.9206, 0.4317, 0.8881],
         [0.2445, 0.8495, 0.8199, 0.1946],
         [0.6700, 0.0704, 0.7777, 0.5099]],

        [[0.1988, 0.8661, 0.3730, 0.5906],
         [0.6488, 0.8544, 0.2441, 0.9657],
         [0.9828, 0.6743, 0.6026, 0.0899]]])
torch.Size([3, 2, 4])
tensor([[[0.0052, 0.9206, 0.4317, 0.8881],
         [0.1988, 0.8661, 0.3730, 0.5906]],

        [[0.2445, 0.8495, 0.8199, 0.1946],
         [0.6488, 0.8544, 0.2441, 0.9657]],

        [[0.6700, 0.0704, 0.7777, 0.5099],
         [0.9828, 0.6743, 0.6026, 0.0899]]])
tensor([[[0.0052, 0.2445, 0.6700],
         [0.9206, 0.8495, 0.0704],
         [0.4317, 0.8199, 0.7777],
         [0.8881, 0.1946, 0.5099]],

        [[0.1988, 0.6488, 0.9828],
         [0.8661, 0.8544, 0.6743],
         [0.3730, 0.2441, 0.6026],
         [0.5906, 0.9657, 0.0899]]])
tensor([[[0.0052, 0.1988],
         [0.2445, 0.6488],
         [0.6700, 0.9828]],

        [[0.9206, 0.8661],
         [0.8495, 0.8544],
         

In [277]:
a=torch.randn(4,3,20,30)
print(a.permute(0,1,3,2).shape)
print(a.permute(3,2,0,1).shape)

torch.Size([4, 3, 30, 20])
torch.Size([30, 20, 4, 3])


### 5.5  broadcast

In [289]:
a=torch.rand(3,4)
b=torch.tensor([1])
print(a)
print(a+b)   #torch中的自动广播机制
c=torch.broadcast_to(b,(3,2))
c

tensor([[0.8942, 0.1815, 0.4194, 0.5685],
        [0.1121, 0.7411, 0.8037, 0.8524],
        [0.8681, 0.8058, 0.0953, 0.9633]])
tensor([[1.8942, 1.1815, 1.4194, 1.5685],
        [1.1121, 1.7411, 1.8037, 1.8524],
        [1.8681, 1.8058, 1.0953, 1.9633]])


tensor([[1, 1],
        [1, 1],
        [1, 1]])

## 6.合并与拆分

### 6.1 cat

In [296]:
a1=torch.rand(4,3,20,20)
a2=torch.rand(3,3,20,20)
print(torch.cat([a1,a2],dim=0).shape)
print("###########fengexian########")
a1=torch.rand(2,3,4)
print(a1)
a2=torch.zeros(2,3,4)
print(torch.cat([a1,a2],dim=0).shape)
print(torch.cat([a1,a2],dim=0))
print(torch.cat([a1,a2],dim=1).shape)
print(torch.cat([a1,a2],dim=1))
print(torch.cat([a1,a2],dim=2).shape)
print(torch.cat([a1,a2],dim=2))

torch.Size([7, 3, 20, 20])
###########fengexian########
tensor([[[0.5109, 0.1396, 0.9074, 0.2790],
         [0.3971, 0.7016, 0.9302, 0.9818],
         [0.3332, 0.6391, 0.7833, 0.0312]],

        [[0.4689, 0.9542, 0.8254, 0.2534],
         [0.5163, 0.3067, 0.6053, 0.5841],
         [0.7934, 0.0980, 0.6390, 0.6861]]])
torch.Size([4, 3, 4])
tensor([[[0.5109, 0.1396, 0.9074, 0.2790],
         [0.3971, 0.7016, 0.9302, 0.9818],
         [0.3332, 0.6391, 0.7833, 0.0312]],

        [[0.4689, 0.9542, 0.8254, 0.2534],
         [0.5163, 0.3067, 0.6053, 0.5841],
         [0.7934, 0.0980, 0.6390, 0.6861]],

        [[0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]]])
torch.Size([2, 6, 4])
tensor([[[0.5109, 0.1396, 0.9074, 0.2790],
         [0.3971, 0.7016, 0.9302, 0.9818],
         [0.3332, 0.6391, 0.

### 6.2 stack

In [303]:
a=torch.randn(2,3,28)
b=torch.randn(2,3,28)
print(torch.stack([a,b],dim=1).shape) #stack合并必须保证两个tensor形状一样
print(torch.stack([a,b],dim=2).shape)
print(torch.stack([a,b],dim=3).shape)

torch.Size([2, 2, 3, 28])
torch.Size([2, 3, 2, 28])
torch.Size([2, 3, 28, 2])


### 6.3 split

In [308]:
a=torch.randn(3,4,5)
print(a)
print(a.split([2,1],dim=0))
print(a.split([4,1],dim=2))

tensor([[[-0.8577,  0.8703,  0.9544,  0.8725, -0.1217],
         [ 1.5322, -0.4122, -0.0192, -0.7328,  0.0299],
         [ 2.4033, -0.3326,  1.2151, -0.3883,  0.8547],
         [-0.4159,  0.6108, -0.7646, -0.0669,  0.5527]],

        [[ 1.9386, -0.9057,  0.9088,  0.1909,  0.3746],
         [ 1.6579, -0.7929, -0.2220,  1.1055, -0.0835],
         [-1.5835,  1.1030,  1.2433,  1.2480,  0.4129],
         [-0.0429,  1.3875,  1.0068,  0.9697, -0.1014]],

        [[-1.2221,  0.8827,  0.6879,  0.7788, -0.2160],
         [ 0.3605,  1.2936, -1.1306, -0.8300,  0.5797],
         [-0.7764, -0.0083, -1.9836,  0.7020,  1.0773],
         [ 0.6268, -1.0865, -0.3782, -0.6626,  0.6187]]])
(tensor([[[-0.8577,  0.8703,  0.9544,  0.8725, -0.1217],
         [ 1.5322, -0.4122, -0.0192, -0.7328,  0.0299],
         [ 2.4033, -0.3326,  1.2151, -0.3883,  0.8547],
         [-0.4159,  0.6108, -0.7646, -0.0669,  0.5527]],

        [[ 1.9386, -0.9057,  0.9088,  0.1909,  0.3746],
         [ 1.6579, -0.7929, -0.2220,  1

### 6.4 chunk,by num

In [309]:
a=torch.randn(3,4,5)
print(a)
print(a.chunk(3,dim=0))
print(a.chunk(2,dim=1))

tensor([[[ 0.0887,  0.6980, -1.5374, -0.6327,  0.8417],
         [-1.0523, -1.4595, -1.4561, -0.2898,  0.7264],
         [-0.6823,  1.0126,  0.1011, -0.5906,  0.6716],
         [ 0.4506, -0.6889, -1.5806, -1.4609, -0.0778]],

        [[ 1.1353,  0.3122, -0.2683,  1.4581, -0.9933],
         [ 0.4153,  0.4118,  0.0569,  0.8171, -0.3081],
         [-0.1617,  0.9038, -1.0966, -0.0186, -1.2336],
         [ 0.0223,  0.3276,  0.8460,  0.4658, -0.5276]],

        [[-0.0139, -1.7129,  0.6736,  1.8076, -1.2072],
         [ 1.4366,  0.2133, -1.0703,  0.4038, -0.0568],
         [-1.1657, -0.4318, -0.0108, -1.0369, -0.7705],
         [-0.4578, -0.6574, -0.6069,  2.1351, -0.7070]]])
(tensor([[[ 0.0887,  0.6980, -1.5374, -0.6327,  0.8417],
         [-1.0523, -1.4595, -1.4561, -0.2898,  0.7264],
         [-0.6823,  1.0126,  0.1011, -0.5906,  0.6716],
         [ 0.4506, -0.6889, -1.5806, -1.4609, -0.0778]]]), tensor([[[ 1.1353,  0.3122, -0.2683,  1.4581, -0.9933],
         [ 0.4153,  0.4118,  0.0569,  

## 7.数学运算

### 7.1 basic

In [26]:
a=torch.arange(1,12,2).reshape(2,3)
b=torch.arange(1,4)
print("a:\n",a)
print("b:\n",b)
print("a+b:\n",a+b,"\n",torch.add(a,b)) #既可以使用“+”，也可以使用torch.add(),下属同理
print('a-b:\n',a-b)
print("a*b:\n",a*b)
print("a/b:\n",a/b)
print("a**b:\n",a**b)
print("b.repeat():\n",b.repeat(2).reshape(2,3)) #复制b为[2,3]的矩阵
c=b.reshape(1,3).repeat(2,1)
print("c:\n",c)
print("a@c:\n",a@c.t(),"\n",torch.matmul(a,c.t()))


a:
 tensor([[ 1,  3,  5],
        [ 7,  9, 11]])
b:
 tensor([1, 2, 3])
a+b:
 tensor([[ 2,  5,  8],
        [ 8, 11, 14]]) 
 tensor([[ 2,  5,  8],
        [ 8, 11, 14]])
a-b:
 tensor([[0, 1, 2],
        [6, 7, 8]])
a*b:
 tensor([[ 1,  6, 15],
        [ 7, 18, 33]])
a/b:
 tensor([[1.0000, 1.5000, 1.6667],
        [7.0000, 4.5000, 3.6667]])
a**b:
 tensor([[   1,    9,  125],
        [   7,   81, 1331]])
b.repeat():
 tensor([[1, 2, 3],
        [1, 2, 3]])
c:
 tensor([[1, 2, 3],
        [1, 2, 3]])
a@c:
 tensor([[22, 22],
        [58, 58]]) 
 tensor([[22, 22],
        [58, 58]])


### 7.2 pow,rsqrt,sum,exp

In [53]:
a=torch.arange(1,23,3).reshape(2,-1)
b=torch.arange(1,5)
print("a:\n",a,"\nb:\n",b)
print("a^2:\n",a.pow(2),"\n",a**2) #a^2表示异或操作
print("sum:\n",a.sum() ,a.sum(0) ,a.sum(1), a.sum(0).sum(0))
print("rsqrt:\n",a.rsqrt())

a:
 tensor([[ 1,  4,  7, 10],
        [13, 16, 19, 22]]) 
b:
 tensor([1, 2, 3, 4])
a^2:
 tensor([[  1,  16,  49, 100],
        [169, 256, 361, 484]]) 
 tensor([[  1,  16,  49, 100],
        [169, 256, 361, 484]])
sum:
 tensor(92) tensor([14, 20, 26, 32]) tensor([22, 70]) tensor(92)
rsqrt:
 tensor([[1.0000, 0.5000, 0.3780, 0.3162],
        [0.2774, 0.2500, 0.2294, 0.2132]])


In [42]:
1^2 #异或操作

3

### 7.3 近似操作：floor(),ceil(),round(),trunc(),frac()

In [57]:
a=torch.tensor(3.14)
b=a+0.5
print("a\n",a,"\nb\n",b)
print(a.floor(),a.ceil(),a.round(),a.trunc(),a.frac())
print(b.floor(),b.ceil(),b.round(),b.trunc(),b.frac())

a
 tensor(3.1400) 
b
 tensor(3.6400)
tensor(3.) tensor(4.) tensor(3.) tensor(3.) tensor(0.1400)
tensor(3.) tensor(4.) tensor(4.) tensor(3.) tensor(0.6400)


### 7.4 clamp 裁剪

In [65]:
a=torch.randn(3,4)
print(a)
print(a.clamp(1))
print(a.clamp(0,1))

tensor([[ 0.1760,  1.6329, -1.5506, -0.5868],
        [-0.1908, -0.8261,  0.3126,  0.7941],
        [ 0.9395,  0.5641, -0.0066, -0.4168]])
tensor([[1.0000, 1.6329, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000]])
tensor([[0.1760, 1.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.3126, 0.7941],
        [0.9395, 0.5641, 0.0000, 0.0000]])
